# Generated by Django 4.2.2 on 2023-07-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('admission_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='Admission No')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('mobile_no', models.CharField(blank=True, max_length=11, null=True, verbose_name='Mobile No')),
                ('religion', models.CharField(blank=True, choices=[('M', 'Muslim'), ('H', 'Hindu')], max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email Address')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='Admission Date')),
            ],
            options={
                'db_table': 'admission',
            },
        ),
    ]
