# Generated by Django 4.2.2 on 2023-07-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_admission_blood_group_admission_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Is Online'),
        ),
    ]
