# Generated by Django 4.2.2 on 2023-07-23 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_admission_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True)),
                ('ocupation', models.CharField(blank=True, choices=[('DOCTOR', 'Doctor'), ('TEACHER', 'Teacher'), ('OTHER', 'Other')], max_length=10, null=True, verbose_name='Guardian Ocupation')),
                ('nid', models.CharField(blank=True, max_length=20, null=True, verbose_name='NID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='guardian_photo/')),
                ('mobile_no', models.CharField(blank=True, max_length=11, null=True, verbose_name='Mobile No')),
                ('is_guardian', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_guardian', to='admission.admission')),
            ],
            options={
                'db_table': 'ad_guardian',
            },
        ),
    ]
