# Generated by Django 4.2.2 on 2023-07-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_admission_institution_guardian_relation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admission',
            table='ad_student',
        ),
    ]
