# Generated by Django 4.2.2 on 2023-08-06 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_alter_branch_options_alter_institution_options'),
        ('admission', '0010_admissiontestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.branch'),
        ),
    ]
