# Generated by Django 4.2.2 on 2023-10-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_remove_examroutine_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='examroutine',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
