# Generated by Django 4.2.2 on 2023-10-14 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0029_alter_classroutine_day'),
        ('exam', '0002_examname'),
    ]

    operations = [
        migrations.AddField(
            model_name='examname',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.session'),
        ),
    ]
