# Generated by Django 4.2.2 on 2023-10-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_examroutine_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamRoutine',
        ),
    ]
