# Generated by Django 4.2.2 on 2023-10-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_examroutine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examroutine',
            name='day',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Exam Day'),
        ),
    ]
