# Generated by Django 4.2.2 on 2024-09-19 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0004_branch_institution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartofAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coa_type', models.CharField(max_length=10, verbose_name='COA Type')),
                ('code', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('income_stat_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Income Statement Type')),
                ('balance_sheet_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Balance Sheet Type')),
                ('direct_posting', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.branch')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_coa_creator', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institution', verbose_name='Institution Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_coa', to='account.chartofaccounts')),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_coa_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chart Of Accounts',
                'db_table': 'acc_coa',
            },
        ),
    ]
