# Generated by Django 4.2.2 on 2024-09-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_chartofaccounts_income_stat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccounts',
            name='keyword',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
