# Generated by Django 4.2.2 on 2024-09-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_chartofaccounts_carry_forward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccounts',
            name='code',
            field=models.BigIntegerField(unique=True),
        ),
    ]
