# Generated by Django 4.2.2 on 2024-09-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_chartofaccounts_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccounts',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
