# Generated by Django 4.2.2 on 2024-09-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_accountbanks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbanks',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
    ]
