# Generated by Django 4.2.2 on 2024-09-25 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_accountbanks_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountbanks',
            name='ip_address',
        ),
    ]
