# Generated by Django 4.2.2 on 2024-09-25 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institution', '0004_branch_institution'),
        ('account', '0010_remove_accountbanks_ip_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountbanks',
            options={'verbose_name': 'Account Bank'},
        ),
        migrations.AlterModelOptions(
            name='accountperiod',
            options={'verbose_name': 'Account Period'},
        ),
        migrations.CreateModel(
            name='AccountLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gl_date', models.DateField()),
                ('credit_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Credit Amount')),
                ('debit_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Debit Amount')),
                ('narration', models.TextField(blank=True, null=True)),
                ('ref_source', models.CharField(blank=True, max_length=100, null=True)),
                ('particulars', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acc_coa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_coa', to='account.chartofaccounts')),
                ('acc_coa_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_ref_coa', to='account.chartofaccounts')),
                ('acc_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.accountperiod')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.branch')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_le_creator', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institution', verbose_name='Institution Name')),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_le_update_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Ledger',
                'db_table': 'acc_ledger',
            },
        ),
    ]
