# Generated by Django 4.2.2 on 2024-09-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_accountbanks_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountledger',
            name='voucher_type',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
