# Generated by Django 4.2.2 on 2024-09-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_accountledger_voucher_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountledger',
            name='voucher_type',
            field=models.CharField(choices=[('PAYMENT', 'Payment'), ('RECEIVE', 'Receive')], max_length=30),
        ),
    ]
