# Generated by Django 4.2.2 on 2024-10-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_accountledger_voucher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccounts',
            name='fin_stat_type',
            field=models.CharField(blank=True, choices=[('BALANCE', 'Balance Sheet'), ('INCOME', 'Income Sheet')], max_length=50, null=True, verbose_name='Financial Statement'),
        ),
    ]
