# Generated by Django 4.2.2 on 2024-10-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_accountledger_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountledger',
            name='voucher_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
