# Generated by Django 4.2.2 on 2024-10-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_accountvoucherdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountvouchermaster',
            name='acc_coa',
        ),
    ]
