# Generated by Django 4.2.2 on 2024-10-30 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_remove_accountvouchermaster_acc_coa'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbanks',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Code'),
        ),
        migrations.AlterField(
            model_name='accountvoucherdetails',
            name='acc_voucher_mst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_voucher_detail', to='account.accountvouchermaster'),
        ),
        migrations.AlterField(
            model_name='accountvouchermaster',
            name='voucher_no',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
