# Generated by Django 4.2.2 on 2024-10-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_accountbanks_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbanks',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
