# Generated by Django 4.2.2 on 2024-10-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_accountbanks_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccounts',
            name='code',
            field=models.BigIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='chartofaccounts',
            constraint=models.UniqueConstraint(fields=('code', 'status', 'institution', 'branch'), name='unique_code_constraint'),
        ),
    ]
