# Generated by Django 4.2.2 on 2024-10-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_accountbanks_account_bank_unique_constraint_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='accountvouchermaster',
            constraint=models.UniqueConstraint(fields=('voucher_no', 'status', 'institution', 'branch'), name='account_ledger_unique_constraint'),
        ),
    ]
