# Generated by Django 4.2.2 on 2024-10-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_remove_accountbanks_account_bank_unique_constraint_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='accountbanks',
            constraint=models.UniqueConstraint(fields=('bank', 'branch_name', 'account_no', 'status', 'institution', 'branch'), name='account_bank_unique_constraint'),
        ),
    ]
