# Generated by Django 4.2.2 on 2023-11-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mach_no', models.CharField(blank=True, max_length=3, null=True)),
                ('card_no', models.CharField(max_length=50)),
                ('atnd_date', models.DateField()),
                ('atnd_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hr_atnd_raw',
            },
        ),
    ]
