# Generated by Django 4.2.2 on 2023-11-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_attendanceraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceraw',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
