# Generated by Django 4.2.2 on 2023-11-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_attendanceraw_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att_date', models.DateField()),
                ('emp_no', models.CharField(max_length=20)),
                ('in_time', models.TimeField()),
                ('in_time2', models.TimeField()),
                ('late', models.IntegerField()),
                ('late2', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('status2', models.BooleanField(default=True)),
                ('out_time', models.TimeField()),
                ('out_time2', models.TimeField()),
                ('ot_hour', models.IntegerField()),
                ('ot_hour2', models.IntegerField()),
                ('extra_ot', models.IntegerField()),
                ('manul_att', models.CharField(blank=True, max_length=50, null=True)),
                ('manual_status', models.CharField(blank=True, max_length=50, null=True)),
                ('deduct_val', models.IntegerField(blank=True, null=True)),
                ('nor_ot', models.IntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('shift_code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_late_grant', models.BooleanField(default=False)),
                ('is_early_packup_grant', models.BooleanField(default=False)),
                ('is_deviation_grant', models.BooleanField(default=False)),
                ('com_id', models.IntegerField(blank=True, null=True)),
                ('others3', models.IntegerField(blank=True, null=True)),
                ('out_time3', models.TimeField(blank=True, null=True)),
                ('row_status', models.CharField(blank=True, max_length=255, null=True)),
                ('others4', models.IntegerField(blank=True, null=True)),
                ('out_time4', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hr_attendance_details',
            },
        ),
    ]
