# Generated by Django 4.2.2 on 2023-11-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0006_desig'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='desig',
            table='hr_desig',
        ),
    ]
