# Generated by Django 4.2.2 on 2023-11-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0007_alter_desig_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(blank=True, max_length=20, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('pay_for_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hr_el_payment',
            },
        ),
    ]
