# Generated by Django 4.2.2 on 2023-11-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0010_holiday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceDetail',
        ),
        migrations.DeleteModel(
            name='AttendanceRaw',
        ),
        migrations.RemoveField(
            model_name='desig',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='desig',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='desig',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='desig',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='ElPayment',
        ),
        migrations.RenameField(
            model_name='leavetype',
            old_name='m_days',
            new_name='max_days',
        ),
        migrations.DeleteModel(
            name='Desig',
        ),
    ]
