# Generated by Django 4.2.2 on 2023-11-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0011_delete_attendancedetail_delete_attendanceraw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
