# Generated by Django 4.2.2 on 2023-11-29 09:42

from django.db import migrations, models
import hrms.models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0012_leavetype_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(max_length=50, validators=[hrms.models.validate_alpha_chars_only], verbose_name='Leave Type Name'),
        ),
    ]
