# Generated by Django 4.2.2 on 2023-11-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0013_alter_leavetype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
