# Generated by Django 4.2.2 on 2023-12-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0014_leavetype_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='is_general_day',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='is_weekly_offday',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='year',
        ),
        migrations.AddField(
            model_name='holiday',
            name='end_date',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holiday',
            name='start_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
