# Generated by Django 4.2.2 on 2024-01-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0016_holiday_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
