# Generated by Django 4.2.2 on 2024-01-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0017_holiday_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
