# Generated by Django 4.2.2 on 2024-01-30 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0019_holiday_holiday_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='type',
        ),
    ]
