# Generated by Django 4.2.2 on 2024-01-30 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0020_remove_holiday_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='holiday_type',
            new_name='type',
        ),
    ]
