# Generated by Django 4.2.2 on 2024-08-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0022_payrollelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollelement',
            name='type_name',
            field=models.CharField(choices=[('Allowance', 'Allowance'), ('Deduction', 'Deduction')], default=None, max_length=255, verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payrollelement',
            name='type',
            field=models.CharField(max_length=2),
        ),
    ]
