# Generated by Django 4.2.2 on 2024-08-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0023_payrollelement_type_name_alter_payrollelement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollelement',
            name='type',
            field=models.IntegerField(editable=False),
        ),
    ]
