# Generated by Django 4.2.2 on 2024-08-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0030_alter_salarysetupdtl_payroll_ele'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollelement',
            name='type_name',
            field=models.CharField(choices=[('Allowance', 'Allowance'), ('Deduction', 'Deduction'), ('Other', 'Other')], max_length=255, verbose_name='Type'),
        ),
    ]
