# Generated by Django 4.2.2 on 2024-08-20 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0031_alter_payrollelement_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarysetupdtl',
            name='salary_setup_mst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_setup_dtl', to='hrms.salarysetupmst'),
        ),
    ]
