# Generated by Django 4.2.2 on 2024-08-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0032_alter_salarysetupdtl_salary_setup_mst'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarysetupdtl',
            name='seq_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ordering'),
        ),
    ]
