# Generated by Django 4.2.2 on 2024-08-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0037_accounttaxdtl'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttaxdtl',
            name='pct',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4, verbose_name='%'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounttaxdtl',
            name='lmt',
            field=models.IntegerField(verbose_name='Limit'),
        ),
    ]
