# Generated by Django 4.2.2 on 2024-04-28 09:30

import communicate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communicate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='notice_board/', validators=[communicate.models.validate_file_size]),
        ),
    ]
