# Generated by Django 4.2.2 on 2024-05-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0051_paymentmethod'),
        ('communicate', '0004_smssendsetup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smssendsetup',
            name='group',
            field=models.ManyToManyField(blank=True, to='setup_app.role'),
        ),
    ]
