# Generated by Django 4.2.2 on 2024-05-14 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0211_alter_classsubject_book_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communicate', '0005_alter_smssendsetup_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smssendsetup',
            name='class_section',
            field=models.ManyToManyField(blank=True, to='academic.classsection'),
        ),
        migrations.AlterField(
            model_name='smssendsetup',
            name='individual',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
