# Generated by Django 4.2.2 on 2024-05-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communicate', '0006_alter_smssendsetup_class_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smssendsetup',
            name='message_body',
            field=models.TextField(blank=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='smssendsetup',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
