# Generated by Django 4.2.2 on 2024-09-09 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0062_alter_processstaffsalarytable_new_payable_amt_and_more'),
        ('institution', '0004_branch_institution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0248_alter_classsubject_book_file'),
        ('setup_app', '0052_activestatus'),
        ('student', '0031_student_std_status_studentstatustransaction'),
        ('communicate', '0007_alter_smssendsetup_message_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('email_recipient_list', models.TextField(default='')),
                ('email_cc_recipient_list', models.TextField(default='')),
                ('sms_recipient_list', models.TextField(default='')),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('mobile_app', models.BooleanField(blank=True, default=False, null=True)),
                ('group', models.BooleanField(default=False)),
                ('individual', models.BooleanField(default=False)),
                ('academic_class', models.BooleanField(default=False)),
                ('birthdays', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_class_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_email_log_academic_class_info', to='academic.classsection')),
                ('academic_class_sections_info', models.ManyToManyField(blank=True, related_name='sms_email_log_academic_class_sections_info', to='academic.section')),
                ('birthdays_staff', models.ManyToManyField(blank=True, related_name='sms_email_log_birthdays_staff', to='staff.staff')),
                ('birthdays_students', models.ManyToManyField(blank=True, related_name='sms_email_log_birthdays_students', to='student.student')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.branch')),
                ('cc_guardians', models.ManyToManyField(blank=True, related_name='sms_email_log_cc_guardians', to='student.guardian')),
                ('cc_staff', models.ManyToManyField(blank=True, related_name='sms_email_log_cc_staff', to='staff.staff')),
                ('cc_students', models.ManyToManyField(blank=True, related_name='sms_email_log_cc_students', to='student.student')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_email_log_creator', to=settings.AUTH_USER_MODEL)),
                ('group_ids', models.ManyToManyField(blank=True, to='setup_app.role')),
                ('individual_guardians', models.ManyToManyField(blank=True, related_name='sms_email_log_individual_guardians', to='student.guardian')),
                ('individual_staff', models.ManyToManyField(blank=True, related_name='sms_email_log_individual_staff', to='staff.staff')),
                ('individual_students', models.ManyToManyField(blank=True, related_name='sms_email_log_individual_students', to='student.student')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institution')),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_email_log_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Email Log',
                'db_table': 'comm_sms_email_log',
            },
        ),
        migrations.CreateModel(
            name='SmsEmailLogAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='sms_email_log_attachments/', verbose_name='Attachment')),
                ('sms_email_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='communicate.smsemaillog')),
            ],
            options={
                'verbose_name': 'SMS Email Log Attachment',
                'db_table': 'comm_sms_email_log_attachments',
            },
        ),
        migrations.DeleteModel(
            name='SmsSendSetup',
        ),
    ]
