# Generated by Django 4.2.2 on 2023-08-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_education_branch_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='desgi_ord',
            field=models.IntegerField(blank=True, null=True, verbose_name='Designation Order'),
        ),
    ]
