# Generated by Django 4.2.2 on 2023-09-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='Staff Code'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='Staff ID'),
        ),
    ]
