# Generated by Django 4.2.2 on 2023-10-09 14:10

from django.db import migrations, models
import staff.models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_alter_education_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Staff Code'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(blank=True, default=staff.models.staff_no, editable=False, max_length=20, null=True, verbose_name='Staff ID'),
        ),
    ]
