# Generated by Django 4.2.2 on 2023-10-11 10:40

from django.db import migrations, models
import staff.models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_staffshift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffshift',
            name='code',
            field=models.CharField(blank=True, default=staff.models.staff_shift_code, max_length=20, null=True),
        ),
    ]
