# Generated by Django 4.2.2 on 2023-10-11 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_alter_staff_religion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffshift',
            old_name='Institution',
            new_name='institution',
        ),
    ]
