# Generated by Django 4.2.2 on 2023-10-22 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_staff_department_staff_designation_staff_shift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='Institution',
            new_name='institution',
        ),
    ]
