# Generated by Django 4.2.2 on 2023-11-25 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0037_day_week_end'),
        ('staff', '0018_remove_education_board_education_edu_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='step',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='education',
            name='edu_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_app.educationboard', verbose_name='Board'),
        ),
    ]
