# Generated by Django 4.2.2 on 2023-11-26 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0038_contracttype'),
        ('staff', '0020_staffpayroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpayroll',
            name='contract_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_app.contracttype'),
        ),
    ]
