# Generated by Django 4.2.2 on 2023-11-26 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0039_maritalstatus'),
        ('staff', '0022_alter_staffpayroll_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='marital_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_marital_status', to='setup_app.maritalstatus'),
        ),
    ]
