# Generated by Django 4.2.2 on 2023-11-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0023_staff_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='emergency_number',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Emergency Contact Number'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Mobile No'),
        ),
    ]
