# Generated by Django 4.2.2 on 2023-11-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0024_staff_emergency_number_alter_staff_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='nid',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='NID'),
        ),
    ]
