# Generated by Django 4.2.2 on 2023-11-27 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrms', '0011_delete_attendancedetail_delete_attendanceraw_and_more'),
        ('staff', '0025_staff_nid'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffBankAccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_title', models.CharField(max_length=255, verbose_name='Account Title')),
                ('account_number', models.CharField(max_length=50, verbose_name='Account Number')),
                ('branch_name', models.CharField(max_length=100, verbose_name='Branch Name')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.accountbank')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_acc_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_acc_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sta_bank_account',
            },
        ),
    ]
