# Generated by Django 4.2.2 on 2023-11-27 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0026_staffbankaccountdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffbankaccountdetails',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staffbankaccountdetails',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_bank_info', to='staff.staff'),
        ),
    ]
