# Generated by Django 4.2.2 on 2023-11-27 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0028_education_branch_education_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffbankaccountdetails',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_info', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='staffpayroll',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='staffsocialmedia',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_media', to='staff.staff'),
        ),
    ]
