# Generated by Django 4.2.2 on 2023-11-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0030_staffleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='doj',
            field=models.DateField(blank=True, null=True, verbose_name='Date Of Join'),
        ),
    ]
