# Generated by Django 4.2.2 on 2023-12-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0033_processattendancedaily'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='last_attn_proc_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
