# Generated by Django 4.2.2 on 2023-12-17 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0034_staff_last_attn_proc_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processattendancedaily',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atten_daily', to='staff.staff'),
        ),
    ]
