# Generated by Django 4.2.2 on 2023-12-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0035_alter_processattendancedaily_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='processattendancedaily',
            name='duration',
            field=models.DurationField(blank=True, editable=False, null=True, verbose_name='Duraion'),
        ),
    ]
