# Generated by Django 4.2.2 on 2023-12-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0038_staffleavetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffleavetransaction',
            name='day_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
