# Generated by Django 4.2.2 on 2023-12-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0039_alter_staffleavetransaction_day_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffleavetransaction',
            name='day_count',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Number of Day'),
        ),
    ]
