# Generated by Django 4.2.2 on 2023-12-19 13:57

from django.db import migrations, models
import staff.models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0040_alter_staffleavetransaction_day_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffleavetransaction',
            name='code',
            field=models.CharField(default=staff.models.leave_code, editable=False, max_length=20, verbose_name='Leave Code'),
        ),
    ]
