# Generated by Django 4.2.2 on 2023-12-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0043_alter_processattendancedaily_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffleavetransaction',
            name='active_start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffleavetransaction',
            name='application_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
