# Generated by Django 4.2.2 on 2023-12-28 11:28

from django.db import migrations, models
import staff.models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0044_alter_staffleavetransaction_active_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffleavetransaction',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='staff_leave_doc/', validators=[staff.models.validate_pdf_file_size], verbose_name='Document'),
        ),
    ]
