# Generated by Django 4.2.2 on 2023-12-28 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0045_staffleavetransaction_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffleavetransaction',
            name='apply_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_leave_trns', to='staff.staff'),
        ),
    ]
