# Generated by Django 4.2.2 on 2024-01-03 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0047_alter_setup_title_alter_setup_type'),
        ('institution', '0004_branch_institution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0046_alter_staffleavetransaction_apply_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffLeaveAppHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approve_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_status', models.ForeignKey(blank=True, limit_choices_to={'parent': 'APPROVAL_STATUS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_status', to='setup_app.setup')),
                ('approve_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff')),
                ('approve_group', models.ForeignKey(blank=True, limit_choices_to={'parent': 'STAFF_LEAVE_APP_HIR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_group', to='setup_app.setup')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.branch', verbose_name='Branch Name')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_trns_his_creator', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institution', verbose_name='Institution Name')),
                ('leave_trns', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffleavetransaction')),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_trns_his_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff_leave_approve_history',
            },
        ),
    ]
