# Generated by Django 4.2.2 on 2024-01-03 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0048_rename_institution_setup_institution'),
        ('staff', '0047_staffleaveapphistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffleaveapphistory',
            name='app_status',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__type': 'APPROVAL_STATUS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_status', to='setup_app.setup'),
        ),
        migrations.AlterField(
            model_name='staffleaveapphistory',
            name='approve_group',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__type': 'STAFF_LEAVE_APP_HIR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_group', to='setup_app.setup'),
        ),
    ]
