# Generated by Django 4.2.2 on 2024-01-03 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0048_rename_institution_setup_institution'),
        ('staff', '0048_alter_staffleaveapphistory_app_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffleavetransaction',
            name='app_status',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__type': 'APPROVAL_STATUS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_status', to='setup_app.setup'),
        ),
    ]
