# Generated by Django 4.2.2 on 2024-05-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0049_alter_staffleavetransaction_app_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffleave',
            name='process_days',
            field=models.IntegerField(default=0),
        ),
    ]
