# Generated by Django 4.2.2 on 2024-05-02 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0050_staffleave_process_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffleaveapphistory',
            name='approve_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='staffleaveapphistory',
            name='leave_trns',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_path', to='staff.staffleavetransaction'),
        ),
    ]
