# Generated by Django 4.2.2 on 2024-05-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0051_alter_staffleaveapphistory_approve_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffleaveapphistory',
            name='approve_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
