# Generated by Django 4.2.2 on 2024-08-07 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields
import staff.models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_branch_institution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0053_attendancedailyraw_device_ip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStaffAttendanceMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=staff.models.staff_atnn_code, editable=False, max_length=15, verbose_name='Code')),
                ('staff_code', models.CharField(blank=True, max_length=100, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('total_day', models.IntegerField(default=0, editable=False)),
                ('present_day', models.IntegerField(default=0)),
                ('absent_day', models.IntegerField(default=0)),
                ('late_day', models.IntegerField(default=0)),
                ('early_gone_day', models.IntegerField(default=0)),
                ('tot_payble_day', models.IntegerField(default=0)),
                ('ot_hour', models.IntegerField(default=0)),
                ('gen_type', models.CharField(default='AUTO', max_length=15)),
                ('tour_day', models.IntegerField(default=0)),
                ('weekend_day', models.IntegerField(default=0)),
                ('holiday_day', models.IntegerField(default=0)),
                ('actual_gross', models.IntegerField(default=0)),
                ('calc_gross', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.branch', verbose_name='Branch Name')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_proc_atnn_mst_creator', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institution', verbose_name='Institution Name')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
                ('staff_payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffpayroll')),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_proc_atnn_mst_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff_proc_out_attn_mst',
            },
        ),
    ]
