# Generated by Django 4.2.2 on 2024-08-31 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institution', '0004_branch_institution'),
        ('staff', '0055_staffstatustransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStaffSalaryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_no', models.CharField(blank=True, max_length=50, null=True)),
                ('staff_name', models.CharField(blank=True, max_length=200, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('bank_acc_no', models.CharField(blank=True, max_length=255, null=True)),
                ('is_hold', models.BooleanField(default=False)),
                ('prl_ele_basic', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('prl_ele_house_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('prl_ele_medical', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('prl_ele_conveyance', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('prl_ele_others_a', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('gross', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('prl_ele_adjustment_a', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('prl_ele_adjustment_d', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('prl_ele_cash_advance', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('prl_ele_donation', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('prl_ele_award', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('prl_ele_ait', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('prl_ele_mobile_bill_d', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('prl_ele_rpf', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('prl_ele_other_d', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('prl_ele_absent_d', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('prl_ele_food_d', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('total_deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('new_payable_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('payable_day', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.branch', verbose_name='Branch Name')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proc_sal_creator', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.designation')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institution', verbose_name='Institution Name')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff')),
                ('staff_payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffpayroll')),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proc_sal_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff_proc_sal_tbl',
            },
        ),
    ]
