# Generated by Django 4.2.2 on 2024-09-02 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0038_accounttaxdtl_pct_alter_accounttaxdtl_lmt'),
        ('staff', '0056_processstaffsalarytable'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpayroll',
            name='salary_Setup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms.salarysetupmst'),
        ),
    ]
