# Generated by Django 4.2.2 on 2024-09-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0057_staffpayroll_salary_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstaffsalarytable',
            name='gross',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
