# Generated by Django 4.2.2 on 2024-09-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0058_alter_processstaffsalarytable_gross'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstaffsalarytable',
            name='prl_ele_basic',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
