# Generated by Django 4.2.2 on 2024-09-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0059_alter_processstaffsalarytable_prl_ele_basic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstaffsalarytable',
            name='prl_ele_conveyance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processstaffsalarytable',
            name='prl_ele_house_rent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processstaffsalarytable',
            name='prl_ele_medical',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processstaffsalarytable',
            name='prl_ele_others_a',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
