# Generated by Django 4.2.2 on 2024-09-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0060_alter_processstaffsalarytable_prl_ele_conveyance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstaffsalarytable',
            name='payable_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
