# Generated by Django 4.2.2 on 2024-09-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0061_alter_processstaffsalarytable_payable_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstaffsalarytable',
            name='new_payable_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processstaffsalarytable',
            name='prl_ele_absent_d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processstaffsalarytable',
            name='prl_ele_adjustment_a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processstaffsalarytable',
            name='prl_ele_adjustment_d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processstaffsalarytable',
            name='prl_ele_ait',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processstaffsalarytable',
            name='prl_ele_award',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processstaffsalarytable',
            name='prl_ele_cash_advance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processstaffsalarytable',
            name='prl_ele_donation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processstaffsalarytable',
            name='prl_ele_food_d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processstaffsalarytable',
            name='prl_ele_mobile_bill_d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processstaffsalarytable',
            name='prl_ele_other_d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processstaffsalarytable',
            name='prl_ele_rpf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processstaffsalarytable',
            name='total_deduction',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
