# Generated by Django 4.2.2 on 2024-10-01 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0052_activestatus'),
        ('staff', '0062_alter_processstaffsalarytable_new_payable_amt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_app.contracttype'),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_app.activestatus'),
        ),
    ]
