# Generated by Django 4.2.2 on 2024-10-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0063_staff_category_staff_staff_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstaffsalarytable',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
