# Generated by Django 4.2.2 on 2024-10-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0064_processstaffsalarytable_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstaffsalarytable',
            name='accounting',
            field=models.BooleanField(default=False),
        ),
    ]
