# Generated by Django 4.2.2 on 2024-12-10 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0040_alter_studentenroll_roll'),
        ('staff', '0067_alter_attendancedailyraw_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedailyraw',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student'),
        ),
    ]
