# Generated by Django 4.2.2 on 2025-01-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0068_attendancedailyraw_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedailyraw',
            name='device_row_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
