# Generated by Django 4.2.2 on 2023-12-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
