# Generated by Django 4.2.2 on 2023-12-31 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields
import fees.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institution', '0004_branch_institution'),
        ('fees', '0002_feestype_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[fees.models.validate_alpha_chars_only], verbose_name='Fees Name Discount')),
                ('code', models.SlugField(max_length=255)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Discount %')),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.branch')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees_discount_creator', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.institution')),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees_discount_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fe_fees_discount',
            },
        ),
        migrations.AddConstraint(
            model_name='feesdiscount',
            constraint=models.CheckConstraint(check=models.Q(('percentage__gte', '0')), name='discount_pct_non_negative'),
        ),
    ]
