# Generated by Django 4.2.2 on 2024-02-25 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0196_alter_classsubject_book_file'),
        ('fees', '0003_feesdiscount_feesdiscount_discount_pct_non_negative'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesMaster',
            fields=[
            ],
            options={
                'verbose_name': 'Fees Master',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('academic.classsection',),
        ),
    ]
