# Generated by Django 4.2.2 on 2024-02-27 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_feesdetails_fees_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feesdetails',
            name='fine_type',
        ),
        migrations.AlterField(
            model_name='feesdetails',
            name='fees_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_detail', to='fees.feesmaster'),
        ),
    ]
