# Generated by Django 4.2.2 on 2024-04-03 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setup_app', '0051_paymentmethod'),
        ('student', '0030_student_birth_cert_file_student_birth_reg_scert_no'),
        ('institution', '0004_branch_institution'),
        ('fees', '0007_remove_feesdetails_fine_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pay_date', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('discount_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Discount Amount')),
                ('fine_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Fine Amount')),
                ('fees_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Fees Amount')),
                ('pay_status', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.branch')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees_trns_creator', to=settings.AUTH_USER_MODEL)),
                ('discount_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.feesdiscount')),
                ('fees_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.feesdetails')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.institution')),
                ('pay_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_app.paymentmethod', verbose_name='Payment Method')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees_trns', to='student.student')),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees_trns_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fees_transaction',
            },
        ),
    ]
