# Generated by Django 4.2.2 on 2024-08-14 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institution', '0004_branch_institution'),
        ('fees', '0009_feestransactiondetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeDetailsBreakDown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('amount', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.branch')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees_dtl_br_dw_creator', to=settings.AUTH_USER_MODEL)),
                ('fees_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feesdetails')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.institution')),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees_dtl_br_dw_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fees_dtl_break_down',
            },
        ),
    ]
