# Generated by Django 4.2.2 on 2024-08-15 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_branch_institution'),
        ('fees', '0010_feedetailsbreakdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedetailsbreakdown',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.branch'),
        ),
        migrations.AlterField(
            model_name='feedetailsbreakdown',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institution'),
        ),
    ]
