# Generated by Django 4.2.2 on 2024-09-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0011_alter_feedetailsbreakdown_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesdetails',
            name='fix_amt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fix Amount'),
        ),
    ]
