# Generated by Django 4.2.2 on 2024-10-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0013_alter_feedetailsbreakdown_fees_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestransaction',
            name='paid_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Paid Amount'),
        ),
    ]
