# Generated by Django 4.2.2 on 2024-10-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0014_feestransaction_paid_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestransaction',
            name='pay_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment Date'),
        ),
    ]
