# Generated by Django 4.2.2 on 2024-11-14 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0065_processstaffsalarytable_accounting'),
        ('academic', '0262_alter_classsubject_book_file'),
        ('fees', '0015_alter_feestransaction_pay_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestransaction',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.classname', verbose_name='Class Name'),
        ),
        migrations.AddField(
            model_name='feestransaction',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.classgroup'),
        ),
        migrations.AddField(
            model_name='feestransaction',
            name='roll',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Class Roll'),
        ),
        migrations.AddField(
            model_name='feestransaction',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.section', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='feestransaction',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.session', verbose_name='Session'),
        ),
        migrations.AddField(
            model_name='feestransaction',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffshift'),
        ),
        migrations.AddField(
            model_name='feestransaction',
            name='student_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feestransaction',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.version', verbose_name='version'),
        ),
    ]
