# Generated by Django 4.2.2 on 2024-11-23 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0031_student_std_status_studentstatustransaction'),
        ('fees', '0016_feestransaction_class_name_feestransaction_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestransaction',
            name='student_enroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.studentenroll'),
        ),
        migrations.AddConstraint(
            model_name='feestransaction',
            constraint=models.UniqueConstraint(fields=('student', 'fees_detail', 'status', 'institution', 'branch'), name='unique_fees_trns_constraint'),
        ),
    ]
