# Generated by Django 4.2.2 on 2024-11-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0017_feestransaction_student_enroll_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feestransaction',
            name='unique_fees_trns_constraint',
        ),
        migrations.AddConstraint(
            model_name='feestransaction',
            constraint=models.UniqueConstraint(fields=('student', 'student_enroll', 'fees_detail', 'status', 'institution', 'branch'), name='unique_fees_trns_constraint'),
        ),
    ]
