# Generated by Django 4.2.2 on 2024-11-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0018_remove_feestransaction_unique_fees_trns_constraint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestype',
            name='category',
            field=models.CharField(blank=True, choices=[('admission', 'Admission'), ('exam', 'Exam'), ('monthly', 'Monthly'), ('others', 'Others')], max_length=20, null=True),
        ),
    ]
