# Generated by Django 4.2.2 on 2025-01-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0019_feestype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestransaction',
            name='is_accounting',
            field=models.BooleanField(default=False),
        ),
    ]
