# Generated by Django 4.2.2 on 2024-11-04 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0004_branch_institution'),
        ('hrms', '0038_accounttaxdtl_pct_alter_accounttaxdtl_lmt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Supplier Code')),
                ('name', models.CharField(max_length=255, verbose_name='Supplier Name')),
                ('short_name', models.CharField(max_length=50, verbose_name='Supplier Short Name')),
                ('address', models.TextField()),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Owner Name')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('opening_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Opening Balance')),
                ('current_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Current Balance')),
                ('con_person', models.CharField(blank=True, max_length=2555, null=True, verbose_name='Contact Person')),
                ('con_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('con_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('type', models.CharField(choices=[('Manufacturer', 'Manufacturer'), ('Importer', 'Importer'), ('Trader', 'Trader'), ('Local', 'Local')], max_length=20, verbose_name='Supplier Type')),
                ('owner_nid', models.CharField(blank=True, max_length=50, null=True, verbose_name='Owner NID')),
                ('bin', models.CharField(blank=True, max_length=20, null=True, verbose_name='BIN Number')),
                ('tin', models.CharField(blank=True, max_length=50, null=True, verbose_name='TIN Number')),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Branch Name')),
                ('account_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Account No.')),
                ('last_trns_date', models.DateTimeField(blank=True, null=True, verbose_name='Last Transaction Date')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms.accountbank', verbose_name='Bank Name')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.branch')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_creator', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institution', verbose_name='Institution Name')),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pur_supplier',
            },
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('name', 'bin', 'status', 'institution', 'branch'), name='supplier_unique_constraint'),
        ),
    ]
