# Generated by Django 4.2.2 on 2024-11-04 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0053_systemcounter'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_app.country'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_app.district'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_app.division'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='thana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_app.thana'),
        ),
    ]
