# Generated by Django 4.2.2 on 2024-11-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_supplier_country_supplier_district_supplier_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Owner Email'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='owner_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='con_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Person Name'),
        ),
    ]
