# Generated by Django 4.2.2 on 2024-11-05 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_branch_institution'),
        ('inventory', '0008_alter_item_def_pur_unit_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0004_purchaseordermaster_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseordermaster',
            options={'verbose_name': 'Purchase Order'},
        ),
        migrations.CreateModel(
            name='PurchaseOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.IntegerField()),
                ('order_qty', models.IntegerField()),
                ('approve_qty', models.IntegerField(blank=True, null=True)),
                ('receive_qty', models.IntegerField(blank=True, null=True)),
                ('uom', models.CharField(max_length=20, verbose_name='UoM')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('other_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('vat_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='VAT %')),
                ('vat_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='VAT Amount')),
                ('dis_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Discount %')),
                ('dis_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Discount Amount')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Total Price')),
                ('net_total_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Net Total Amount')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.branch')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pur_ord_dtl_creator', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.institution')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('order_mst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_details', to='purchase.purchaseordermaster')),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pur_ord_dtl_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pur_order_dtl',
            },
        ),
    ]
