# Generated by Django 4.2.2 on 2024-11-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_alter_purchaseordermaster_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderdetails',
            old_name='line_id',
            new_name='line',
        ),
    ]
