# Generated by Django 4.2.2 on 2024-11-06 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institution', '0004_branch_institution'),
        ('setup_app', '0053_systemcounter'),
        ('inventory', '0008_alter_item_def_pur_unit_price_and_more'),
        ('purchase', '0006_rename_line_id_purchaseorderdetails_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodSReceiptNoteMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='GRN Number')),
                ('grn_date', models.DateField()),
                ('purchase_type', models.CharField(choices=[('LOCAL', 'Local')], max_length=20)),
                ('total_rec_qty', models.IntegerField(blank=True, null=True, verbose_name='Total Receive Quantity')),
                ('total_dis_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Discount Amount')),
                ('total_ord_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Order Amount')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.branch')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_rece_notes_mst_creator', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.institution')),
                ('pay_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_app.paymentmethod')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.supplier')),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_rece_notes_mst_update_by', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse', verbose_name='Receiving Warehouse')),
            ],
            options={
                'verbose_name': 'Goods Receive Notes',
                'db_table': 'pur_goods_receive_notes_mst',
            },
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptnotemaster',
            constraint=models.UniqueConstraint(fields=('code', 'status', 'institution', 'branch'), name='goods_receive_notes_mst_unique_constraint'),
        ),
    ]
