# Generated by Django 4.2.2 on 2024-11-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_goodsreceiptnotemaster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceiptnotemaster',
            name='total_ord_amt',
        ),
        migrations.AddField(
            model_name='goodsreceiptnotemaster',
            name='total_rec_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Receive Amount'),
        ),
    ]
