# Generated by Django 4.2.2 on 2024-11-06 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_branch_institution'),
        ('inventory', '0008_alter_item_def_pur_unit_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0008_remove_goodsreceiptnotemaster_total_ord_amt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceiptNotesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField()),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rcv_qty', models.IntegerField()),
                ('rcv_uom', models.CharField(blank=True, max_length=20, null=True)),
                ('rcv_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rcv_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_total_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.branch')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_rece_notes_dtl_creator', to=settings.AUTH_USER_MODEL)),
                ('goods_receipt_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grn_details', to='purchase.goodsreceiptnotemaster')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.institution')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_rece_notes_dtl_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pur_goods_receive_notes_dtl',
            },
        ),
    ]
