# Generated by Django 4.2.2 on 2024-11-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_goodsreceiptnotesdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptnotemaster',
            name='total_net_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Net Amount'),
        ),
        migrations.AlterField(
            model_name='goodsreceiptnotemaster',
            name='grn_date',
            field=models.DateField(verbose_name='GRN Date'),
        ),
    ]
