# Generated by Django 4.2.2 on 2024-11-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_goodsreceiptnotemaster_total_net_amt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptnotemaster',
            name='confirm_with_pay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goodsreceiptnotemaster',
            name='confirm_without_pay',
            field=models.BooleanField(default=False),
        ),
    ]
