# Generated by Django 4.2.2 on 2024-12-01 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_branch_institution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setup_app', '0053_systemcounter'),
        ('purchase', '0013_supplierpaymentmst'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPaymentDtl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField()),
                ('pay_amt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payment Amount')),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.branch')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sup_pay_dtl_creator', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.institution')),
                ('pay_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_app.paymentmethod')),
                ('supplier_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.supplierpaymentmst')),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sup_pay_dtl_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pur_supplier_payment_dtl',
            },
        ),
    ]
