# Generated by Django 4.2.2 on 2024-12-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0014_supplierpaymentdtl'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpaymentmst',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supplierpaymentmst',
            name='total_pay_amt',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Total Payment Amount'),
        ),
    ]
