# Generated by Django 4.2.2 on 2025-01-06 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0016_alter_supplierpaymentmst_total_pay_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpaymentdtl',
            name='supplier_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_details', to='purchase.supplierpaymentmst'),
        ),
        migrations.AlterField(
            model_name='supplierpaymentmst',
            name='grn_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_code', to='purchase.goodsreceiptnotemaster', verbose_name='GRN Code'),
        ),
    ]
