# Generated by Django 4.2.2 on 2023-07-23 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institution', '0001_initial'),
        ('academic', '0002_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': '2. Section'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': '1. Section'},
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Class Code')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Class Name')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_creator', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institution')),
                ('section', models.ManyToManyField(to='academic.section')),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '3. Class',
                'db_table': 'ac_class',
            },
        ),
    ]
