# Generated by Django 4.2.2 on 2023-07-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_class_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
