# Generated by Django 4.2.2 on 2023-07-25 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institution', '0001_initial'),
        ('academic', '0007_alter_version_options_subject_institution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Room Code')),
                ('location', models.CharField(blank=True, choices=[('GROUND', 'Ground Floor'), ('1st', '1st Floor'), ('1st', '1st Floor')], max_length=20, null=True)),
                ('building', models.CharField(blank=True, max_length=100, null=True, verbose_name='Building Name')),
                ('room_no', models.CharField(blank=True, max_length=10, null=True, verbose_name='Room No.')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_room_creator', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institution')),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_room_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '6. Class Room',
                'db_table': 'ac_class_room',
            },
        ),
    ]
