# Generated by Django 4.2.2 on 2023-07-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='location',
            field=models.CharField(blank=True, choices=[('GROUND', 'Ground Floor'), ('1st', '1st Floor'), ('2nd', '2nd Floor')], max_length=20, null=True),
        ),
    ]
