# Generated by Django 4.2.2 on 2023-07-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_classperiod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': '2. Section'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': '3. Session'},
        ),
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Session'),
        ),
    ]
