# Generated by Django 4.2.2 on 2023-07-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_alter_section_options_alter_session_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': '3. Section'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': '2. Session'},
        ),
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.IntegerField(blank=True, null=True, verbose_name='Session'),
        ),
    ]
