# Generated by Django 4.2.2 on 2023-07-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_alter_section_options_alter_session_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ManyToManyField(to='academic.subject'),
        ),
    ]
