# Generated by Django 4.2.2 on 2023-08-06 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_class_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='section',
        ),
        migrations.RemoveField(
            model_name='class',
            name='subject',
        ),
    ]
