# Generated by Django 4.2.2 on 2023-08-13 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0018_classname_branch_classperiod_branch_classroom_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/', verbose_name='Book Image'),
        ),
        migrations.RemoveField(
            model_name='classsubject',
            name='subject',
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.subject'),
        ),
    ]
