# Generated by Django 4.2.2 on 2023-09-19 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0021_classname_section_classname_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.classname'),
        ),
    ]
