# Generated by Django 4.2.2 on 2023-09-19 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0022_classsubject_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubject',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.classname', verbose_name='Class Name'),
        ),
    ]
