# Generated by Django 4.2.2 on 2023-09-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0023_alter_classsubject_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Session'),
        ),
    ]
