# Generated by Django 4.2.2 on 2023-10-14 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0017_day_sl_no'),
        ('academic', '0026_alter_classroutine_options_remove_classname_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroutine',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_app.day', verbose_name='Day'),
        ),
    ]
