# Generated by Django 4.2.2 on 2023-10-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0027_alter_classroutine_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroutine',
            name='day',
            field=models.CharField(choices=[('SUNDAY', 'SUNDAY'), ('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THURSDAY')], max_length=20, verbose_name='Day'),
        ),
    ]
