# Generated by Django 4.2.2 on 2023-10-15 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0020_alter_floortype_name'),
        ('academic', '0029_alter_classroutine_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='floor_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_app.floortype'),
        ),
    ]
