# Generated by Django 4.2.2 on 2023-10-15 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0020_alter_floortype_name'),
        ('academic', '0031_remove_classroom_location_alter_classroom_floor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsubject',
            name='class_section',
        ),
        migrations.AddField(
            model_name='classsubject',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Subject Code'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.section'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='floor_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor', to='setup_app.floortype'),
        ),
    ]
