# Generated by Django 4.2.2 on 2023-10-17 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0021_subjecttype'),
        ('academic', '0035_classsubject_session_classsubject_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_app.subjecttype', verbose_name='Subject Type'),
        ),
    ]
