# Generated by Django 4.2.2 on 2023-10-19 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0021_subjecttype'),
        ('academic', '0037_classroutinemst_classroutiinedtl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroutinemst',
            options={'verbose_name': 'Class Routine'},
        ),
        migrations.RemoveField(
            model_name='classroutiinedtl',
            name='day',
        ),
        migrations.AddField(
            model_name='classroutinemst',
            name='day',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='setup_app.day', verbose_name='Day'),
            preserve_default=False,
        ),
    ]
