# Generated by Django 4.2.2 on 2023-10-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0038_alter_classroutinemst_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classperiod',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Class Duraion'),
        ),
    ]
