# Generated by Django 4.2.2 on 2023-10-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0039_alter_classperiod_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classperiod',
            name='duration',
            field=models.DurationField(blank=True, editable=False, null=True, verbose_name='Class Duraion'),
        ),
    ]
