# Generated by Django 4.2.2 on 2023-10-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0040_alter_classperiod_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to='book_file/', verbose_name='Book File'),
        ),
    ]
