# Generated by Django 4.2.2 on 2023-11-25 08:57

import academic.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0083_alter_classsubject_book_file_classgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classgroup',
            options={'verbose_name': 'Class Group'},
        ),
        migrations.AlterField(
            model_name='classsubject',
            name='book_file',
            field=academic.models.PDFFileField(blank=True, null=True, upload_to='book_file/', validators=[academic.models.validate_pdf_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Book File'),
        ),
    ]
