# Generated by Django 4.2.2 on 2023-11-25 10:15

import academic.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0084_alter_classgroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='classsubject',
            name='book_file',
            field=academic.models.PDFFileField(blank=True, null=True, upload_to='book_file/', validators=[academic.models.validate_pdf_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Book File'),
        ),
    ]
