# Generated by Django 4.2.2 on 2023-12-05 11:05

import academic.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0040_alter_day_long_name_alter_day_short_name_days'),
        ('academic', '0120_alter_classsubject_book_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroutine',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_app.days', verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='classroutinemst',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_app.days', verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='classsubject',
            name='book_file',
            field=academic.models.PDFFileField(blank=True, null=True, upload_to='book_file/', validators=[academic.models.validate_pdf_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Book File'),
        ),
    ]
