# Generated by Django 4.2.2 on 2024-11-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_model_model_model_unique_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'verbose_name': 'Model'},
        ),
    ]
