# Generated by Django 4.2.2 on 2024-11-03 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institution', '0004_branch_institution'),
        ('inventory', '0005_alter_model_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Item Code')),
                ('name', models.CharField(max_length=255, verbose_name='Item Name')),
                ('type', models.CharField(choices=[('FINISHED_GOODS', 'Finished Goods'), ('RAW_MATERIALS', 'Raw Materials')], max_length=50)),
                ('keyword', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Keyword')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Item ')),
                ('purchase_item', models.BooleanField(default=True)),
                ('purchase_uom', models.CharField(blank=True, max_length=10, null=True)),
                ('def_pur_unit_price', models.IntegerField(default=0, verbose_name='Regular Purchase Price')),
                ('min_pur_qty', models.IntegerField(default=1, verbose_name='Min Purchase Qty')),
                ('default_uom', models.CharField(blank=True, max_length=10, null=True)),
                ('sales_item', models.BooleanField(default=False)),
                ('sales_uom', models.CharField(blank=True, max_length=10, null=True)),
                ('min_sales_qty', models.IntegerField(default=1, verbose_name='Min Sales Qty')),
                ('def_sales_price', models.IntegerField(default=0, verbose_name='Default Sales Price')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.branch')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.brand', verbose_name='Brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category', verbose_name='Item Category')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_creator', to=settings.AUTH_USER_MODEL)),
                ('default_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institution', verbose_name='Institution Name')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.model', verbose_name='Item Model')),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'db_table': 'inv_item',
            },
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('name', 'keyword', 'status', 'institution', 'branch'), name='item_unique_constraint'),
        ),
    ]
