# Generated by Django 4.2.2 on 2024-11-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item_item_item_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Item Description'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('code', 'status', 'institution', 'branch'), name='item_code_unique_constraint'),
        ),
    ]
