# Generated by Django 4.2.2 on 2024-11-11 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institution', '0004_branch_institution'),
        ('inventory', '0008_alter_item_def_pur_unit_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('uom', models.CharField(max_length=10)),
                ('quantity', models.IntegerField(default=0)),
                ('book_quantity', models.IntegerField(default=0)),
                ('sefty_alter_qty', models.IntegerField(default=0)),
                ('unit_cost_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Unit Cost Value')),
                ('weighted_unit_cost_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Weighted Unit Cost Value')),
                ('last_receive_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.branch')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_mst_creator', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institution', verbose_name='Institution Name')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_item', to='inventory.item')),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_mst_update_by', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_warehose', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Stock Master',
                'db_table': 'inv_stock_master',
            },
        ),
        migrations.AddConstraint(
            model_name='stockmaster',
            constraint=models.UniqueConstraint(fields=('item', 'warehouse', 'status', 'institution', 'branch'), name='stock_mast_constraint'),
        ),
    ]
