# Generated by Django 4.2.2 on 2024-11-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_stockmaster_stockmaster_stock_mast_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmaster',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Stock Quantity'),
        ),
        migrations.AlterField(
            model_name='stockmaster',
            name='uom',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='UoM'),
        ),
    ]
