# Generated by Django 4.2.2 on 2024-11-11 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institution', '0004_branch_institution'),
        ('purchase', '0011_goodsreceiptnotemaster_confirm_with_pay_and_more'),
        ('inventory', '0010_alter_stockmaster_quantity_alter_stockmaster_uom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmaster',
            options={'verbose_name': 'Stock'},
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='Voucher Type')),
                ('invoice_no', models.CharField(max_length=50, verbose_name='Invoice No')),
                ('uom', models.CharField(blank=True, max_length=10, null=True, verbose_name='UoM')),
                ('trns_date', models.DateTimeField(blank=True, null=True)),
                ('trns_type', models.CharField(max_length=25, verbose_name='Transaction Type')),
                ('quantity', models.IntegerField(default=0)),
                ('vat_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='VAT Amount')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.branch')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_trns_creator', to=settings.AUTH_USER_MODEL)),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_trns_from', to='inventory.warehouse')),
                ('grn_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.goodsreceiptnotesdetails', verbose_name='GRN Details')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institution', verbose_name='Institution Name')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.supplier', verbose_name='Supplier')),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_trns_update_by', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_trns_warhouse', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'db_table': 'inv_stock_transaction',
            },
        ),
        migrations.AddConstraint(
            model_name='stocktransaction',
            constraint=models.UniqueConstraint(fields=('grn_detail', 'status', 'institution', 'branch'), name='stock_trns_constraint'),
        ),
    ]
