# Generated by Django 4.2.2 on 2024-11-21 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_stockmaster_options_stocktransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='from_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_trns_from', to='inventory.warehouse'),
        ),
    ]
