# Generated by Django 4.2.2 on 2023-09-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_authentication_branch_authentication_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('GUARDIAN', 'Guardian'), ('ACCOUNTANT', 'Accountant')], max_length=30, null=True),
        ),
    ]
