# Generated by Django 4.2.2 on 2023-09-20 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0015_alter_permission_can_view'),
        ('authentication', '0003_alter_authentication_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentication',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_app.role'),
        ),
    ]
