# Generated by Django 4.2.2 on 2023-09-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0015_alter_permission_can_view'),
        ('authentication', '0004_authentication_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authentication',
            name='role',
        ),
        migrations.AddField(
            model_name='authentication',
            name='role',
            field=models.ManyToManyField(related_name='user_role', to='setup_app.role'),
        ),
    ]
