# Generated by Django 4.2.2 on 2023-09-20 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setup_app', '0006_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Menu Name')),
                ('slug', models.SlugField(blank=True, max_length=55, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='menu_icon/', verbose_name='Icon')),
                ('create_permission', models.BooleanField(default=False)),
                ('view_permission', models.BooleanField(default=False)),
                ('edit_permission', models.BooleanField(default=False)),
                ('delete_permission', models.BooleanField(default=False)),
                ('sl_no', models.IntegerField(blank=True, null=True, verbose_name='Ordering')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_creator', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_menu', to='setup_app.menu')),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 's_menu',
            },
        ),
    ]
