# Generated by Django 4.2.2 on 2023-09-20 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0007_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='create_permission',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='delete_permission',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='edit_permission',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='view_permission',
        ),
    ]
