# Generated by Django 4.2.2 on 2023-09-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0008_remove_menu_create_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='level',
            field=models.IntegerField(blank=True, null=True, verbose_name='Menu Level'),
        ),
    ]
