# Generated by Django 4.2.2 on 2023-09-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0011_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='can_create',
            field=models.BooleanField(default=False, verbose_name='Create'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='can_delete',
            field=models.BooleanField(default=False, verbose_name='Delete'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='can_update',
            field=models.BooleanField(default=False, verbose_name='Update'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='can_view',
            field=models.BooleanField(default=False, verbose_name='View'),
        ),
    ]
