# Generated by Django 4.2.2 on 2023-09-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0012_alter_permission_can_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodgroup',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gender',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='occupation',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='relation',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='religion',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
