# Generated by Django 4.2.2 on 2023-09-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0014_permission_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='can_view',
            field=models.BooleanField(default=True, verbose_name='View'),
        ),
    ]
