# Generated by Django 4.2.2 on 2023-10-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0016_permission_created_at_permission_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='sl_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
