# Generated by Django 4.2.2 on 2023-10-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0019_alter_grade_name_alter_grade_point_alter_grade_sl_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='point',
            field=models.FloatField(verbose_name='Grade Point'),
        ),
    ]
