# Generated by Django 4.2.2 on 2023-10-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0019_floortype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floortype',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Floor Type'),
        ),
    ]
