# Generated by Django 4.2.2 on 2023-10-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0020_alter_grade_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='point',
            field=models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Grade Point'),
        ),
    ]
