# Generated by Django 4.2.2 on 2023-10-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0022_alter_grade_point_grade_grade_point_non_negative'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(check=models.Q(('point__lte', 5)), name='grade_point_not_over_five'),
        ),
    ]
