# Generated by Django 4.2.2 on 2023-11-01 14:21

from django.db import migrations, models
import setup_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0025_alter_educationboard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=50, validators=[setup_app.models.validate_alpha_chars_only], verbose_name='District Name'),
        ),
    ]
