# Generated by Django 4.2.2 on 2023-11-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0029_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='dist_code',
            new_name='coun_code',
        ),
    ]
