# Generated by Django 4.2.2 on 2023-11-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0032_remove_country_branch_remove_country_institution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='district',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='thana',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='thana',
            name='institution',
        ),
    ]
