# Generated by Django 4.2.2 on 2023-11-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0033_remove_district_branch_remove_district_institution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationboard',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='educationboard',
            name='institution',
        ),
    ]
