# Generated by Django 4.2.2 on 2023-11-06 15:53

from django.db import migrations, models
import setup_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0034_remove_educationboard_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='coun_code',
            field=models.CharField(max_length=4, validators=[setup_app.models.validate_alpha_chars_only], verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='district',
            name='dist_code',
            field=models.CharField(max_length=4, validators=[setup_app.models.validate_alpha_chars_only], verbose_name='District Code'),
        ),
        migrations.AlterField(
            model_name='division',
            name='divi_code',
            field=models.CharField(max_length=4, validators=[setup_app.models.validate_alpha_chars_only], verbose_name='Division Code'),
        ),
        migrations.AlterField(
            model_name='educationboard',
            name='board_code',
            field=models.CharField(max_length=3, validators=[setup_app.models.validate_alpha_chars_only], verbose_name='Board Code'),
        ),
        migrations.AlterField(
            model_name='thana',
            name='thana_code',
            field=models.CharField(max_length=4, validators=[setup_app.models.validate_alpha_chars_only], verbose_name='Thana Code'),
        ),
    ]
