# Generated by Django 4.2.2 on 2023-11-07 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0035_alter_country_coun_code_alter_district_dist_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_app.division'),
        ),
        migrations.AddField(
            model_name='thana',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_app.district'),
        ),
    ]
