# Generated by Django 4.2.2 on 2023-11-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0036_district_division_thana_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='week_end',
            field=models.BooleanField(default=False),
        ),
    ]
