# Generated by Django 4.2.2 on 2023-12-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0040_alter_day_long_name_alter_day_short_name_days'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
    ]
