# Generated by Django 4.2.2 on 2023-12-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0042_attendancetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='icon_text',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='', verbose_name='Icon Text'),
        ),
    ]
