# Generated by Django 4.2.2 on 2023-12-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0043_menu_icon_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Icon Text'),
        ),
    ]
