# Generated by Django 4.2.2 on 2024-01-03 11:10

from django.db import migrations, models
import setup_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0045_alter_menu_icon_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='code',
            field=models.CharField(blank=True, default=setup_app.models.setup_code, max_length=20, null=True, verbose_name='Setup Code'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Setup Type'),
        ),
    ]
