# Generated by Django 4.2.2 on 2024-01-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0046_alter_setup_code_alter_setup_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Setup Title'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Setup Type'),
        ),
    ]
