# Generated by Django 4.2.2 on 2024-01-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0047_alter_setup_title_alter_setup_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setup',
            old_name='Institution',
            new_name='institution',
        ),
    ]
