# Generated by Django 4.2.2 on 2024-01-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0048_rename_institution_setup_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancetype',
            name='display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancetype',
            name='ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
