# Generated by Django 4.2.2 on 2023-09-14 10:44

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_guardian_user_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_no',
            field=models.CharField(blank=True, default=student.models.generate_student_no, editable=False, max_length=15, null=True, verbose_name='Student No'),
        ),
    ]
