# Generated by Django 4.2.2 on 2023-09-14 11:16

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_guardian_guardian_no_alter_guardian_admission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardian',
            old_name='admission',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='guardian',
            name='guardian_no',
            field=models.CharField(blank=True, default=student.models.generate_guardian_no, editable=False, max_length=15, null=True, verbose_name='Guardian No'),
        ),
    ]
