# Generated by Django 4.2.2 on 2023-09-19 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0001_initial'),
        ('student', '0007_alter_guardian_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='ocupation',
        ),
        migrations.AddField(
            model_name='guardian',
            name='occupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_app.setup', verbose_name='guardian_occupation'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_gender', to='setup_app.setup'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_relation', to='setup_app.setup'),
        ),
    ]
