# Generated by Django 4.2.2 on 2023-09-20 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0006_relation'),
        ('student', '0008_remove_guardian_ocupation_guardian_occupation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_gender', to='setup_app.gender'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='occupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_app.occupation', verbose_name='guardian_occupation'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_relation', to='setup_app.relation'),
        ),
        migrations.AlterField(
            model_name='student',
            name='blood_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_b_group', to='setup_app.bloodgroup'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_gender', to='setup_app.gender'),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_religion', to='setup_app.religion'),
        ),
    ]
