# Generated by Django 4.2.2 on 2023-10-29 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_guardian_gender_alter_guardian_occupation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Institution',
            new_name='institution',
        ),
    ]
