# Generated by Django 4.2.2 on 2023-10-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_studentenroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenroll',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentenroll',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
