# Generated by Django 4.2.2 on 2023-10-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_studentenroll_end_date_studentenroll_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenroll',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
