# Generated by Django 4.2.2 on 2023-11-14 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_studentenroll_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenroll',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enroll', to='student.student', verbose_name='Student'),
        ),
    ]
