# Generated by Django 4.2.2 on 2023-11-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_studentenroll_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenroll',
            name='roll',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Class Roll'),
        ),
    ]
