# Generated by Django 4.2.2 on 2023-11-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_alter_studentenroll_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='step',
            field=models.IntegerField(default=1),
        ),
    ]
