# Generated by Django 4.2.2 on 2023-11-25 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_staff_step_alter_education_edu_board'),
        ('student', '0019_studentenroll_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffshift'),
        ),
    ]
