# Generated by Django 4.2.2 on 2023-11-28 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_student_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenroll',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enroll', to='student.student', verbose_name='Student'),
        ),
    ]
