# Generated by Django 4.2.2 on 2024-01-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_processstattendancedaily'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenroll',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
