# Generated by Django 4.2.2 on 2024-01-21 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_studentenroll_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstattendancedaily',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student'),
        ),
    ]
