# Generated by Django 4.2.2 on 2024-01-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_alter_processstattendancedaily_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstattendancedaily',
            name='process_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
