# Generated by Django 4.2.2 on 2024-01-21 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0176_alter_classsubject_book_file'),
        ('student', '0025_processstattendancedaily_process_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstattendancedaily',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.classname', verbose_name='Class Name'),
        ),
        migrations.AlterField(
            model_name='processstattendancedaily',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='processstattendancedaily',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.session', verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='processstattendancedaily',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.version', verbose_name='version'),
        ),
    ]
