# Generated by Django 4.2.2 on 2024-01-21 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_alter_processstattendancedaily_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstattendancedaily',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='std_atten_daily', to='student.student'),
        ),
    ]
