# Generated by Django 4.2.2 on 2024-02-05 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0191_alter_classsubject_book_file'),
        ('setup_app', '0050_holidaytype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0049_alter_staffleavetransaction_app_status'),
        ('institution', '0004_branch_institution'),
        ('student', '0027_alter_processstattendancedaily_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLeaveTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=student.models.leave_code, editable=False, max_length=20, verbose_name='Leave Code')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('tran_type', models.CharField(blank=True, max_length=20, null=True)),
                ('day_count', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Number of Day')),
                ('application_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('add_during_leave', models.TextField(blank=True, null=True)),
                ('reason_for_leave', models.TextField(blank=True, null=True)),
                ('student_code', models.CharField(blank=True, max_length=20, null=True)),
                ('roll', models.CharField(blank=True, max_length=15, null=True, verbose_name='Class Roll')),
                ('document', models.FileField(blank=True, null=True, upload_to='std_leave_doc/', validators=[student.models.validate_pdf_file_size], verbose_name='Document')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('active_start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('active_end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_status', models.ForeignKey(blank=True, limit_choices_to={'parent__type': 'APPROVAL_STATUS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='std_approval_status', to='setup_app.setup')),
                ('apply_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='std_leave_trns', to='student.student')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.branch', verbose_name='Branch Name')),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.classname', verbose_name='Class Name')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='std_trns_creator', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.classgroup')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institution', verbose_name='Institution Name')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.section', verbose_name='Section')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.session', verbose_name='Session')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffshift')),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='std_trns_update_by', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.version', verbose_name='version')),
            ],
            options={
                'db_table': 'std_leave_trns',
            },
        ),
    ]
