# Generated by Django 4.2.2 on 2024-02-05 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0049_alter_staffleavetransaction_app_status'),
        ('student', '0028_studentleavetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentleavetransaction',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='std_leave_responsible', to='staff.staff'),
        ),
    ]
