# Generated by Django 4.2.2 on 2024-02-24 13:50

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_studentleavetransaction_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_cert_file',
            field=models.FileField(blank=True, null=True, upload_to='birth_regi/', validators=[student.models.validate_pdf_file_size], verbose_name='জন্ম নিবন্ধন সনদ'),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_reg_scert_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Birth Registration Certificate No'),
        ),
    ]
