# Generated by Django 4.2.2 on 2024-12-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0039_studentenroll_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenroll',
            name='roll',
            field=models.IntegerField(blank=True, null=True, verbose_name='Class Roll'),
        ),
    ]
