# Generated by Django 4.2.2 on 2024-12-31 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institution', '0004_branch_institution'),
        ('student', '0040_alter_studentenroll_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Previous Institution Name')),
                ('address', models.TextField()),
                ('class_name', models.CharField(max_length=255)),
                ('roll_no', models.IntegerField()),
                ('document', models.FileField(blank=True, null=True, upload_to='pre_edu_doc/', verbose_name='Document')),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.branch', verbose_name='Branch Name')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_edu_creator', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institution', verbose_name='Institution Name')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_education', to='student.student')),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_edu_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'std_previous_edu',
            },
        ),
    ]
