# Generated by Django 4.2.2 on 2025-01-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0041_previouseducation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studentenroll',
            constraint=models.UniqueConstraint(fields=('student', 'version', 'session', 'class_name', 'status', 'institution', 'branch'), name='unique_std_enroll_constraint'),
        ),
        migrations.AddConstraint(
            model_name='studentenroll',
            constraint=models.UniqueConstraint(fields=('version', 'session', 'class_name', 'shift', 'group', 'section', 'roll', 'status', 'institution', 'branch'), name='unique_std_enroll_roll_const'),
        ),
    ]
