# Generated by Django 4.2.2 on 2025-01-16 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_branch_institution'),
        ('student', '0042_studentenroll_unique_std_enroll_constraint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.branch'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institution', verbose_name='Institution Name'),
        ),
    ]
