# Generated by Django 4.2.2 on 2023-08-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_remove_institution_parent_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': '2. Branch'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': '1. Institution'},
        ),
    ]
