# Generated by Django 4.2.2 on 2023-09-04 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_alter_branch_options_alter_institution_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institution'),
        ),
    ]
